export const mastersConfig = {
  departments: {
    title: 'Department',
    plural: 'Departments',
    description: 'Manage your company departments',
    endpoint: 'departments',
    moduleKey: 'departments',
    columns: [
      { key: 'departmentName', label: 'Department' },
      { key: 'description', label: 'Description' },
    ],
    fields: [
      { name: 'departmentName', label: 'Department Name', type: 'text', required: true },
      { name: 'description', label: 'Description', type: 'textarea' },
    ],
  },
  designations: {
    title: 'Designation',
    plural: 'Designations',
    description: 'Manage designations within departments',
    endpoint: 'designations',
    moduleKey: 'designations',
    columns: [
      { key: 'designationName', label: 'Designation' },
      { key: 'departmentId', label: 'Department', type: 'ref' },
    ],
    fields: [
      { name: 'departmentId', label: 'Department', type: 'select', refEndpoint: 'departments', refLabel: 'departmentName', required: true },
      { name: 'designationName', label: 'Designation Name', type: 'text', required: true },
    ],
  },
  clients: {
    title: 'Client',
    plural: 'Clients',
    description: 'Manage your client and project records',
    endpoint: 'clients',
    moduleKey: 'clients',
    columns: [
      { key: 'clientName', label: 'Client Name' },
      { key: 'projectName', label: 'Project' },
      { key: 'mobileNo', label: 'Mobile No' },
      { key: 'emailId', label: 'Email' },
    ],
    fields: [
      { name: 'projectName', label: 'Project Name', type: 'text', required: true },
      { name: 'clientName', label: 'Client Name', type: 'text', required: true },
      { name: 'ongoingProjects', label: 'Ongoing Projects', type: 'text' },
      { name: 'location', label: 'Location', type: 'text' },
      { name: 'gstin', label: 'GSTIN', type: 'text' },
      { name: 'contactName', label: 'Contact Name', type: 'text' },
      { name: 'mobileNo', label: 'Mobile No', type: 'text' },
      { name: 'emailId', label: 'Email ID', type: 'email' },
      { name: 'address', label: 'Address', type: 'textarea' },
    ],
  },
  suppliers: {
    title: 'Supplier',
    plural: 'Suppliers',
    description: 'Manage supplier and vendor records',
    endpoint: 'suppliers',
    moduleKey: 'suppliers',
    columns: [
      { key: 'companyName', label: 'Company' },
      { key: 'contactName', label: 'Contact' },
      { key: 'mobileNo', label: 'Mobile No' },
      { key: 'city', label: 'City' },
    ],
    fields: [
      { name: 'companyName', label: 'Company Name', type: 'text', required: true },
      { name: 'contactName', label: 'Contact Name', type: 'text', required: true },
      { name: 'address', label: 'Address', type: 'textarea' },
      { name: 'city', label: 'City', type: 'text' },
      { name: 'state', label: 'State', type: 'text' },
      { name: 'pincode', label: 'Pincode', type: 'text' },
      { name: 'mobileNo', label: 'Mobile No', type: 'text' },
      { name: 'mobileNo2', label: 'Mobile No 2', type: 'text' },
      { name: 'emailId', label: 'Email ID', type: 'email' },
      { name: 'panNo', label: 'PAN No', type: 'text' },
      { name: 'gstin', label: 'GSTIN', type: 'text' },
      { name: 'bankDetails.accountHolderName', label: 'Account Holder Name', type: 'text' },
      { name: 'bankDetails.accountNumber', label: 'Account Number', type: 'text' },
      { name: 'bankDetails.bankName', label: 'Bank Name', type: 'text' },
      { name: 'bankDetails.branchName', label: 'Branch Name', type: 'text' },
      { name: 'bankDetails.ifscCode', label: 'IFSC Code', type: 'text' },
      { name: 'remarks', label: 'Remarks', type: 'textarea' },
    ],
  },
  labourers: {
    title: 'Labourer',
    plural: 'Labourers',
    description: 'Manage labourer records',
    endpoint: 'labourers',
    moduleKey: 'labourers',
    columns: [
      { key: 'code', label: 'Code' },
      { key: 'name', label: 'Name' },
      { key: 'mobileNo', label: 'Mobile No' },
    ],
    fields: [
      { name: 'code', label: 'Code', type: 'text', required: true },
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'mobileNo', label: 'Mobile No', type: 'text' },
      { name: 'referredBy', label: 'Referred By', type: 'text' },
      { name: 'address', label: 'Address', type: 'textarea' },
      { name: 'pan', label: 'PAN', type: 'text' },
      { name: 'gst', label: 'GST', type: 'text' },
      { name: 'bankDetails.accountHolderName', label: 'Account Holder Name', type: 'text' },
      { name: 'bankDetails.accountNumber', label: 'Account Number', type: 'text' },
      { name: 'bankDetails.bankName', label: 'Bank Name', type: 'text' },
      { name: 'bankDetails.branchName', label: 'Branch Name', type: 'text' },
      { name: 'bankDetails.ifscCode', label: 'IFSC Code', type: 'text' },
    ],
  },
  employees: {
    title: 'Employee',
    plural: 'Employees',
    description: 'Manage employee master records',
    endpoint: 'employees',
    moduleKey: 'employees',
    columns: [
      { key: 'empCode', label: 'Code' },
      { key: 'empName', label: 'Name' },
      { key: 'personalMobNo', label: 'Mobile No' },
      { key: 'departmentId', label: 'Department', type: 'ref' },
    ],
    fields: [
      { name: 'empCode', label: 'Employee Code', type: 'text', required: true, section: 'Personal Information' },
      { name: 'empName', label: 'Employee Name', type: 'text', required: true, section: 'Personal Information' },
      { name: 'dateOfBirth', label: 'Date of Birth', type: 'date', required: true, section: 'Personal Information' },
      { name: 'gender', label: 'Gender', type: 'select', required: true, options: ['Male', 'Female', 'Other'], section: 'Personal Information' },
      { name: 'personalMobNo', label: 'Personal Mobile No', type: 'text', required: true, section: 'Contact Information' },
      { name: 'officeMobNo', label: 'Office Mobile No', type: 'text', required: true, section: 'Contact Information' },
      { name: 'emailId', label: 'Email ID', type: 'email', section: 'Contact Information' },
      { name: 'departmentId', label: 'Department', type: 'select', refEndpoint: 'departments', refLabel: 'departmentName', required: true, section: 'Employment Information' },
      { name: 'designationId', label: 'Designation', type: 'select', refEndpoint: 'designations', refLabel: 'designationName', section: 'Employment Information' },
      { name: 'siteId', label: 'Site', type: 'select', refEndpoint: 'sites', refLabel: 'siteName', section: 'Employment Information' },
      { name: 'dateOfJoining', label: 'Date of Joining', type: 'date', required: true, section: 'Employment Information' },
      { name: 'aadhaarNo', label: 'Aadhaar No', type: 'text', required: true, section: 'Identity Information' },
      { name: 'panNo', label: 'PAN No', type: 'text', section: 'Identity Information' },
      { name: 'pfNo', label: 'PF No', type: 'text', section: 'Identity Information' },
      { name: 'fatherSpouseName', label: 'Father/Spouse Name', type: 'text', required: true, section: 'Family Information' },
      { name: 'fatherSpouseMobNo', label: 'Father/Spouse Mobile No', type: 'text', required: true, section: 'Family Information' },
      { name: 'basicPay', label: 'Basic Pay', type: 'number', required: true, section: 'Salary Information' },
      { name: 'bankAccountNo', label: 'Bank Account No', type: 'text', section: 'Bank Information' },
      { name: 'bankName', label: 'Bank Name', type: 'text', section: 'Bank Information' },
      { name: 'bankBranch', label: 'Bank Branch', type: 'text', section: 'Bank Information' },
      { name: 'ifscCode', label: 'IFSC Code', type: 'text', section: 'Bank Information' },
      { name: 'uniformIssuedOn', label: 'Uniform Issued On', type: 'date', section: 'Other Information' },
      { name: 'remarks1', label: 'Remarks 1', type: 'textarea', section: 'Other Information' },
      { name: 'remarks2', label: 'Remarks 2', type: 'textarea', section: 'Other Information' },
    ],
  },
  expenses: {
    title: 'Expense',
    plural: 'Expenses',
    description: 'Manage expense categories',
    endpoint: 'expenses',
    moduleKey: 'expenses',
    columns: [{ key: 'expenseName', label: 'Expense Name' }],
    fields: [{ name: 'expenseName', label: 'Expense Name', type: 'text', required: true }],
  },
  'item-categories': {
    title: 'Item Category',
    plural: 'Item Categories',
    description: 'Manage item categories',
    endpoint: 'item-categories',
    moduleKey: 'itemCategories',
    columns: [
      { key: 'code', label: 'Code' },
      { key: 'categoryName', label: 'Category Name' },
    ],
    fields: [
      { name: 'code', label: 'Code', type: 'text', required: true },
      { name: 'categoryName', label: 'Category Name', type: 'text', required: true },
    ],
  },
  'item-uoms': {
    title: 'Item UOM',
    plural: 'Item UOMs',
    description: 'Manage units of measurement',
    endpoint: 'item-uoms',
    moduleKey: 'itemUoms',
    columns: [
      { key: 'code', label: 'Code' },
      { key: 'uomName', label: 'UOM Name' },
    ],
    fields: [
      { name: 'code', label: 'Code', type: 'text', required: true },
      { name: 'uomName', label: 'UOM Name', type: 'text', required: true },
    ],
  },
  items: {
    title: 'Item',
    plural: 'Items',
    description: 'Manage inventory items',
    endpoint: 'items',
    moduleKey: 'items',
    columns: [
      { key: 'code', label: 'Code' },
      { key: 'itemName', label: 'Item Name' },
      { key: 'itemCategoryId', label: 'Category', type: 'ref' },
      { key: 'tax', label: 'Tax %' },
    ],
    fields: [
      { name: 'code', label: 'Code', type: 'text', required: true },
      { name: 'itemName', label: 'Item Name', type: 'text', required: true },
      { name: 'itemCategoryId', label: 'Item Category', type: 'select', refEndpoint: 'item-categories', refLabel: 'categoryName', required: true },
      { name: 'itemUomId', label: 'Item UOM', type: 'select', refEndpoint: 'item-uoms', refLabel: 'uomName', required: true },
      { name: 'tax', label: 'Tax (%)', type: 'number' },
    ],
  },
  'labour-types': {
    title: 'Labour Type',
    plural: 'Labour Types',
    description: 'Manage labour type master',
    endpoint: 'labour-types',
    moduleKey: 'labourTypes',
    columns: [{ key: 'labourType', label: 'Labour Type' }],
    fields: [{ name: 'labourType', label: 'Labour Type', type: 'text', required: true }],
  },
  'site-types': {
    title: 'Site Type',
    plural: 'Site Types',
    description: 'Manage site type master',
    endpoint: 'site-types',
    moduleKey: 'siteTypes',
    columns: [{ key: 'siteType', label: 'Site Type' }],
    fields: [{ name: 'siteType', label: 'Site Type', type: 'text', required: true }],
  },
  sites: {
    title: 'Site',
    plural: 'Sites',
    description: 'Manage construction sites',
    endpoint: 'sites',
    moduleKey: 'sites',
    columns: [
      { key: 'code', label: 'Code' },
      { key: 'siteName', label: 'Site Name' },
      { key: 'siteTypeId', label: 'Site Type', type: 'ref' },
    ],
    fields: [
      { name: 'code', label: 'Code', type: 'text', required: true },
      { name: 'siteName', label: 'Site Name', type: 'text', required: true },
      { name: 'siteTypeId', label: 'Site Type', type: 'select', refEndpoint: 'site-types', refLabel: 'siteType', required: true },
      { name: 'projectManagerId', label: 'Project Manager', type: 'select', refEndpoint: 'employees', refLabel: 'empName' },
      { name: 'siteInchargeId', label: 'Site Incharge', type: 'select', refEndpoint: 'employees', refLabel: 'empName' },
      { name: 'qsDataEntryId', label: 'QS Data Entry', type: 'select', refEndpoint: 'employees', refLabel: 'empName' },
    ],
  },
  'vehicle-types': {
    title: 'Vehicle Type',
    plural: 'Vehicle Types',
    description: 'Manage vehicle type master',
    endpoint: 'vehicle-types',
    moduleKey: 'vehicleTypes',
    columns: [{ key: 'vehicleType', label: 'Vehicle Type' }],
    fields: [{ name: 'vehicleType', label: 'Vehicle Type', type: 'text', required: true }],
  },
  trucks: {
    title: 'Truck',
    plural: 'Trucks',
    description: 'Manage trucks and vehicles assigned to sites',
    endpoint: 'trucks',
    moduleKey: 'trucks',
    columns: [
      { key: 'vehicleNo', label: 'Vehicle No' },
      { key: 'siteId', label: 'Site', type: 'ref' },
      { key: 'vehicleTypeId', label: 'Vehicle Type', type: 'ref' },
    ],
    fields: [
      { name: 'vehicleNo', label: 'Vehicle No', type: 'text', required: true },
      { name: 'siteId', label: 'Site', type: 'select', refEndpoint: 'sites', refLabel: 'siteName', required: true },
      { name: 'vehicleTypeId', label: 'Vehicle Type', type: 'select', refEndpoint: 'vehicle-types', refLabel: 'vehicleType', required: true },
    ],
  },
  works: {
    title: 'Work',
    plural: 'Works',
    description: 'Manage work items and their units',
    endpoint: 'works',
    moduleKey: 'works',
    columns: [
      { key: 'workName', label: 'Work Name' },
      { key: 'unitId', label: 'Unit', type: 'ref' },
    ],
    fields: [
      { name: 'workName', label: 'Work Name', type: 'text', required: true },
      { name: 'unitId', label: 'Unit', type: 'select', refEndpoint: 'item-uoms', refLabel: 'uomName', required: true },
    ],
  },
  'filling-stations': {
    title: 'Filling Station',
    plural: 'Filling Stations',
    description: 'Manage fuel filling stations',
    endpoint: 'filling-stations',
    moduleKey: 'fillingStations',
    columns: [
      { key: 'stationName', label: 'Station Name' },
      { key: 'location', label: 'Location' },
    ],
    fields: [
      { name: 'stationName', label: 'Station Name', type: 'text', required: true },
      { name: 'location', label: 'Location', type: 'text' },
    ],
  },
};

export const sidebarGroups = [
  {
    isDirect: true,
    title: 'Dashboard',
    icon: 'LayoutDashboard',
    path: '/dashboard',
    moduleKey: 'dashboard',
  },

  {
    title: 'Main Masters',
    icon: 'Layers',
    items: [
      { label: 'Site Type', path: '/masters/site-types', moduleKey: 'siteTypes', icon: 'MapPinned' },
      { label: 'Site', path: '/masters/sites', moduleKey: 'sites', icon: 'MapPin' },
      { label: 'Item Category', path: '/masters/item-categories', moduleKey: 'itemCategories', icon: 'FolderTree' },
      { label: 'Item UOM', path: '/masters/item-uoms', moduleKey: 'itemUoms', icon: 'Ruler' },
      { label: 'Item Master', path: '/masters/items', moduleKey: 'items', icon: 'Package' },
      { label: 'Work Master', path: '/masters/works', moduleKey: 'works', icon: 'Construction' },
      { label: 'Labour Type', path: '/masters/labour-types', moduleKey: 'labourTypes', icon: 'Hammer' },
      { label: 'Vehicle Type', path: '/masters/vehicle-types', moduleKey: 'vehicleTypes', icon: 'CarFront' },
      { label: 'Trucks', path: '/masters/trucks', moduleKey: 'trucks', icon: 'Truck' },
      { label: 'Filling Stations', path: '/masters/filling-stations', moduleKey: 'fillingStations', icon: 'Fuel' },
      { label: 'Expenses Master', path: '/masters/expenses', moduleKey: 'expenses', icon: 'Receipt' },
    ],
  },
  {
    title: 'People Masters',
    icon: 'Users',
    items: [
      { label: 'Department', path: '/people/departments', moduleKey: 'departments', icon: 'Building' },
      { label: 'Designation', path: '/people/designations', moduleKey: 'designations', icon: 'IdCard' },
      { label: 'Client', path: '/people/clients', moduleKey: 'clients', icon: 'Handshake' },
      { label: 'Supplier', path: '/people/suppliers', moduleKey: 'suppliers', icon: 'Truck' },
      { label: 'Labourer', path: '/people/labourers', moduleKey: 'labourers', icon: 'HardHat' },
      { label: 'Employee', path: '/people/employees', moduleKey: 'employees', icon: 'UserRound' },
    ],
  },
  {
    title: 'Administration',
    icon: 'ShieldCheck',
    items: [
      { label: 'Users', path: '/admin/users', moduleKey: 'users', icon: 'Users' },
      { label: 'Roles', path: '/admin/roles', moduleKey: 'roles', icon: 'KeyRound' },
      { label: 'Audit Logs', path: '/admin/audit-logs', moduleKey: 'auditLogs', icon: 'ScrollText' },
    ],
  },
  {
    title: 'Settings',
    icon: 'Settings',
    items: [
      { label: 'Company Profile', path: '/settings/company-profile', moduleKey: 'company', icon: 'Building2' },
      { label: 'Appearance', path: '/settings/appearance', moduleKey: null, icon: 'Palette' },
      { label: 'Security', path: '/settings/security', moduleKey: null, icon: 'Lock' },
    ],
  },
];
